# Generated by Django 4.1.7 on 2023-03-28 10:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='publications',
            field=models.ManyToManyField(related_name='user_posts', to='posts.post', verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscribers',
            field=models.ManyToManyField(related_name='user_subs', to=settings.AUTH_USER_MODEL, verbose_name='Подписчики'),
        ),
        migrations.AddField(
            model_name='account',
            name='subscriptions',
            field=models.ManyToManyField(related_name='user_subscribers', to=settings.AUTH_USER_MODEL, verbose_name='Подписки'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='posts', verbose_name='Аватар'),
        ),
    ]
