# Generated by Django 4.1.7 on 2023-04-20 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_likes_count'),
        ('accounts', '0002_account_publications_account_subscribers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscribers',
        ),
        migrations.RemoveField(
            model_name='account',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='account',
            name='liked_posts',
            field=models.ManyToManyField(related_name='user_likes', to='posts.post', verbose_name='Понравившиеся публикации'),
        ),
        migrations.AlterField(
            model_name='account',
            name='avatar',
            field=models.ImageField(upload_to='user_pic', verbose_name='Аватар'),
        ),
    ]
