# Generated by Django 3.2 on 2023-04-21 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20230421_1225'),
        ('accounts', '0003_remove_account_publications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='liked_posts',
            field=models.ManyToManyField(related_name='user_likes', to='posts.Post', verbose_name='Лайки'),
        ),
    ]
